### PR TITLE
Add minimal setuptools config to setup.cfg

### PR DESCRIPTION
**Pull request by benber86**

### CODE REVIEW

**Comment by chanhosuh** [comment]
Nice job with the `setup.cfg`.  More or less what I would have done (not sure this is praise or not ;)).  However a few things:

1. Package name should be `curvesim` not `CurveSim`.

2. We don't use namespace packages.
```
[options]
packages = find:
```

3. As for the dep requirements, I would agree the `setup.cfg` is the right place.  Right now we have a `requirements_base.txt` file with an additional `requirements_dev.txt` planned. They are pinned on exact versions but we were planning on loosening to bounds.  

    It would be better to include the specified versions in the `setup.cfg` though as that seems to be a more manageable (and standard) setup.  Please include them and we can deprecate the `requirements_base.txt` (periodically creating the `requirements.txt` via `pip install -e`).  We haven't figured out what the bounds should be, but you are welcome to figure those out :)

4. IANAL, but I think this description should be changed:
    > description = Simulate Curve.finance pools

   to something that reflects the permissionless nature of the pools:
   > description = Simulate Curve pools

    as "Curve Finance" is sometimes used to mean Swiss Stake GmbH.

**Comment by chanhosuh** [comment]
`long_description_content_type = text/markdown` is necessary, otherwise the `twine` upload borks (expects reStructuredText by default).

**Comment by benber86** [comment]
Made suggested changes. For the lower bounds on packages in `install_requires`, I just used the earliest version of each package to support python 3.10 as I didn't want to start playing with environment markers, but do let me know if that is too restrictive.

**Review by chanhosuh — APPROVED** [review]
Everything works, including the twine upload.

**Pull request merged**
